version: '3'

services:
  db:
    image: mysql:8.0
    container_name: api-db
    ports:
      - '${DB_PORT}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./data/docker/volumes/mysql/:/var/lib/mysql
